### ISSUE TITLE
Copy & Paste 

### ISSUE THREAD

**Issue by vladiacob** [Gottox/terminal.js#106]
Can you explain me if exists any simple solution to make ctl+c & ctl+v or cmd+c & cmd+v on macOS to work ? Thanks.

**Comment by wmaciel** [comment]
I would say allowing these shortcuts on a terminal are a bit tricky.
Ctrl C, for example, is the default shortcut to interrupting the foreground process.

I am working on trying to allow copying and pasting trough right-clicks of the mouse though.

**Comment by Gottox** [comment]
there are APIs for that. http://codebits.glennjones.net/editing/getclipboarddata.htm so yes, it's possible.

**Comment by Gottox** [comment]
Support for copy and paste is in terminal.js. Please check if it breaks anything else as I changed some of the focus handling.
