### ISSUE TITLE
Last div wider than the pre tag

### ISSUE THREAD

**Issue by wmaciel** [Gottox/terminal.js#112]
The last div element appears to be too wide.

When the pre element receives focus, the last div becomes visible trough the blue focus halo. It is possible to see that it is sticking out a bit.

I think it might be because it is not set as visibility:hidden

**Comment by Gottox** [comment]
The last div is actually there to measure the width of the terminal. Can you provide a screenshot?

**Comment by wmaciel** [comment]
![div_stick_out](https://cloud.githubusercontent.com/assets/5845424/17788894/9792667e-6544-11e6-916e-4dfd605ff1a7.jpg)

This is what I see

**Comment by wmaciel** [comment]
It only happens after I call temstate resize

**Comment by wmaciel** [comment]
That was actually a bug in my code, I am so sorry.
