### ISSUE TITLE
support double-width character

### ISSUE THREAD

**Issue by kevinptt0323** [Gottox/terminal.js#119]
It will be incorrect if there is double-width characters.
```
it("double width characters", function() {
  var t = newTermState();
  t.write("ab");
  t.mvCursor(-2,0);
  t.write("\u4e00"); // '一' (chinese)
  expect(t.toString()).to.be("\u4e00"); // expect error
});
```
Maybe you can use [wcwidth](https://www.npmjs.com/package/wcwidth) or [string-width](https://www.npmjs.com/package/string-width) to determine the length of string.

**Comment by Gottox** [comment]
Is there a way in Javascript to detect double with characters?
