### ISSUE TITLE
Cursor position in a full line

### ISSUE THREAD

**Issue by kevinptt0323** [Gottox/terminal.js#120]
In `test/term_state.js`, test case `sets cursor` expects the position of cursor must be outside of terminal.
Should it be (0, 1) instead of (10, 0)?
```js
it("sets cursor", function() {
	var t = newTermState(10, 10);
	t.write("1234567890");
	expect(t.cursor.x).to.be(10);
	expect(t.cursor.y).to.be(0);
});
```

**Comment by kevinptt0323** [comment]
Another test case which won't be passed but usual (I guess).
```js
it("breaks lines 2", function() {
	var t = newTermState(10, 10);
	t.write("1234567890");
	expect(t.toString()).to.be("1234567890\n");
	t.write("1");
	expect(t.toString()).to.be("1234567890\n1");
});
```

**Comment by Gottox** [comment]
Hi!

Thanks for the issue. Yes, there's definitely something wrong here. The cursor is allowed to be at the edge of the screen.

Try open an xterm, execute ```cat > /dev/zero``` to be sure there's no readline involved and press [space] to move the cursor to the end of the line, the cursor wraps for the first character in the new line, not for the last in the line before.

But your second testcase does triggers the wrong behavior nonetheless. The "a" should definitely move to the next line. instead it replaces "0".


```
.write("1234567890")
+----------+
|1234567890| <
|          |   
+----------+   
           ^   Curser should be here at (10,0)

.write("a")
+----------+
|1234567890| 
|a         | <  
+----------+   
  ^            Curser should be here at (1,1)
```
