### ISSUE TITLE
Can not input ~ on a Mac

### ISSUE THREAD

**Issue by Dignifiedquire** [Gottox/terminal.js#97]
I just tried this, and found that on a Mac I can not input `~` into the terminal when typing `Alt+N` (the default keyboard combination on mac for `~`).

**Comment by Gottox** [comment]
Does this happen with node-webterminal?

**Comment by Dignifiedquire** [comment]
I used https://github.com/Gottox/node-webterm with manually updated terminal.js to the latest version.

**Comment by Gottox** [comment]
@Dignifiedquire Do you use a german keyboard layout and can you retry it with an US layout? (`~` is `SHIFT` + the key left to `1` )

**Comment by Dignifiedquire** [comment]
Yes I'm using a German keyboard

**Comment by Gottox** [comment]
Does the current version fix this issue? If not please try master.
